"""
Generate Si_UnitBalance Excel balance sheet from JSON dump + config.
Reads Si_UnitBalance_Dump.json (generated by mod) and overlay config.
Run: E:/Anaconda/python.exe build_balance_sheet.py
"""
import json
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# ── Paths ──
DUMP_PATH = r"E:\Steam\steamapps\common\Silica Dedicated Server\Mods\Si_UnitBalance_Dump.json"
CONFIG_PATH = r"E:\Steam\steamapps\common\Silica Dedicated Server\Mods\Si_UnitBalance_Config.json"
OUTPUT_PATH = r"C:\Users\schwe\Projects\Si_UnitBalance\Si_UnitBalance_Sheet.xlsx"

# ── Load data ──
with open(DUMP_PATH, "r") as f:
    dump = json.load(f)
with open(CONFIG_PATH, "r") as f:
    config = json.load(f)

units_cfg = config.get("units", {})
tech_cfg = config.get("tech_time", {})
DEFAULT_TECH_TIME = 30
all_units = dump["units"]
prod_tree = dump["production_tree"]

# ── Skip list: entries that aren't real game units ──
SKIP_NAMES = {
    "Spawn Point", "Unit Spawner", "Anchor", "Zone", "Sports Car",
    "Troop Transport",
}
# Tech tier entries (shown on separate sheet)
TECH_PREFIXES = ("Alpha ", "Beta ", "Gamma ", "Delta ", "Theta ",
                 "Lambda ", "Sigma ", "Omega ", "Mark ")

def is_tech_tier(name):
    return any(name.startswith(p) for p in TECH_PREFIXES)

# ── Faction classification ──

def classify_faction(unit):
    """Return 'Sol', 'Centauri', 'Alien', or None."""
    f = unit.get("faction", "")
    if f == "Sol":
        return "Sol"
    if f == "Centauri":
        return "Centauri"
    if f == "Alien":
        return "Alien"
    return None

# ── Build faction data ──
sol_structures, sol_units = [], []
cent_structures, cent_units = [], []
alien_structures, alien_units = [], []

for u in all_units:
    name = u["name"]
    if name in SKIP_NAMES or is_tech_tier(name):
        continue
    # Worms are Team_AlienWorms — skip for main sheets
    if u.get("team") == "Team_AlienWorms":
        continue

    faction = classify_faction(u)
    is_struct = u.get("is_structure", False)

    if faction == "Sol":
        if is_struct:
            sol_structures.append(u)
        else:
            sol_units.append(u)
    elif faction == "Centauri":
        if is_struct:
            cent_structures.append(u)
        else:
            cent_units.append(u)
    elif faction == "Alien":
        if is_struct:
            alien_structures.append(u)
        else:
            alien_units.append(u)

# ── Sort helpers ──
# Sort structures by: Headquarters first, then factories, then turrets
STRUCT_ORDER = {
    "Headquarters": 0, "Refinery": 1, "Barracks": 2, "Research Facility": 3,
    "Light Factory": 4, "Heavy Factory": 5, "Air Factory": 6,
    "Ultra Heavy Factory": 7, "Silo": 8, "Radar Station": 9,
    "Turret": 10, "Heavy Turret": 11, "Anti-Air Rocket Turret": 12,
    "Fusion Reactor": 13, "Outpost": 14, "Solar Panel": 15,
    # Alien
    "Nest": 0, "Node": 1, "Bio Cache": 2,
    "Lesser Spawning Cyst": 3, "Greater Spawning Cyst": 4,
    "Grand Spawning Cyst": 5, "Colossal Spawning Cyst": 6,
    "Quantum Cortex": 7, "Thorn Spire": 8, "Hive Spire": 9,
}

# Sort units by production building, then tier, then cost
FACTORY_ORDER = {
    "Barracks": 0, "Light Factory": 1, "Heavy Factory": 2,
    "Ultra Heavy Factory": 3, "Air Factory": 4,
    # Alien
    "Lesser Spawning Cyst": 0, "Greater Spawning Cyst": 1,
    "Grand Spawning Cyst": 2, "Colossal Spawning Cyst": 3,
}

def struct_sort_key(u):
    return STRUCT_ORDER.get(u["name"], 99)

def unit_sort_key(u):
    return (FACTORY_ORDER.get(u["built_at"], 99),
            u.get("min_tier", -1),
            u.get("cost", 0))

sol_structures.sort(key=struct_sort_key)
cent_structures.sort(key=struct_sort_key)
alien_structures.sort(key=struct_sort_key)
sol_units.sort(key=unit_sort_key)
cent_units.sort(key=unit_sort_key)
alien_units.sort(key=unit_sort_key)

# ══════════════════════════════════════════════════════════════
# CONFIG HELPERS
# ══════════════════════════════════════════════════════════════

def get_cfg(name, key, default=None):
    entry = units_cfg.get(name, {})
    return entry.get(key, default)

def modded_val(name, vanilla, key):
    mult = get_cfg(name, key)
    if mult is None:
        return vanilla
    return vanilla * mult

def modded_int(name, vanilla, key):
    return max(1, round(modded_val(name, vanilla, key)))

# ══════════════════════════════════════════════════════════════
# STYLES
# ══════════════════════════════════════════════════════════════

HEADER_FONT = Font(bold=True, color="FFFFFF", size=9)
HEADER_FILL_SOL = PatternFill("solid", fgColor="2E5090")
HEADER_FILL_CENT = PatternFill("solid", fgColor="8B0000")
HEADER_FILL_ALIEN = PatternFill("solid", fgColor="2D6B2D")
HEADER_FILL_TECH = PatternFill("solid", fgColor="5C3D7A")
SUBHEADER_FONT = Font(bold=True, size=9)
SUBHEADER_FILL = PatternFill("solid", fgColor="D9E1F2")
CHANGED_FILL = PatternFill("solid", fgColor="FFFFCC")
STRUCT_FILL = PatternFill("solid", fgColor="F2F2F2")
THIN_BORDER = Border(
    left=Side(style="thin"), right=Side(style="thin"),
    top=Side(style="thin"), bottom=Side(style="thin"),
)

def style_header(ws, row, fill, cols):
    for c in range(1, cols + 1):
        cell = ws.cell(row=row, column=c)
        cell.font = HEADER_FONT
        cell.fill = fill
        cell.alignment = Alignment(horizontal="center", wrap_text=True)
        cell.border = THIN_BORDER

def style_subheader(ws, row, cols):
    for c in range(1, cols + 1):
        cell = ws.cell(row=row, column=c)
        cell.font = SUBHEADER_FONT
        cell.fill = SUBHEADER_FILL
        cell.border = THIN_BORDER

def style_row(ws, row, cols, is_struct=False, changed=None):
    changed = changed or set()
    for c in range(1, cols + 1):
        cell = ws.cell(row=row, column=c)
        cell.border = THIN_BORDER
        cell.alignment = Alignment(horizontal="center", vertical="center")
        if c in changed:
            cell.fill = CHANGED_FILL
        elif is_struct:
            cell.fill = STRUCT_FILL
    ws.cell(row=row, column=1).alignment = Alignment(horizontal="left", vertical="center")

# ══════════════════════════════════════════════════════════════
# COLUMNS
# ══════════════════════════════════════════════════════════════

COLUMNS = [
    # 1-2: Identity
    "Name", "Built At",
    # 3-4: Cost (vanilla / modded)
    "V.Cost", "M.Cost",
    # 5-6: Build time
    "V.Build(s)", "M.Build(s)",
    # 7-8: Tier
    "V.Tier", "M.Tier",
    # 9-10: HP
    "V.HP", "M.HP",
    # 11-12: Movement
    "MoveSpd", "FlySpd",
    # 13-18: Creature Attack Primary
    "Atk.Range", "Atk.Spread", "Atk.Proj",
    "Proj.Spd", "Proj.Life", "InstHit",
    # 19-24: Creature Attack Secondary
    "Atk2.Range", "Atk2.Spread", "Atk2.Proj",
    "Proj2.Spd", "Proj2.Life", "InstHit2",
    # 25-28: Vehicle Turret Primary
    "VT.Intv", "VT.Spread", "VT.Mag", "VT.Reload",
    # 29-31: Vehicle Turret Secondary
    "VT2.Intv", "VT2.Spread", "VT2.Mag",
    # 32-33: Detection
    "FoW", "TargDist",
    # 34: MaxDist (build distance for structures)
    "MaxDist",
    # 35-42: Mod config multipliers
    "DmgM", "PSpdM", "RngM", "AccM", "MagM", "FRM", "MvSpdM", "TrnRM", "BuildRad",
    # 43: Notes from config
    "Notes",
]
NC = len(COLUMNS)

def v(x):
    """Display: 0/None/False -> '-', True -> 'Yes', else keep."""
    if x == 0 or x is None or x is False:
        return "-"
    if x is True:
        return "Yes"
    if isinstance(x, float):
        # Clean display: remove trailing zeros
        if x == int(x):
            return int(x)
        return round(x, 4)
    return x

# ══════════════════════════════════════════════════════════════
# WRITE FACTION SHEET
# ══════════════════════════════════════════════════════════════

def write_sheet(wb, title, structures, units, hfill):
    ws = wb.create_sheet(title=title)

    # Header
    row = 1
    for ci, cn in enumerate(COLUMNS, 1):
        ws.cell(row=row, column=ci, value=cn)
    style_header(ws, row, hfill, NC)
    row += 1

    def write_entries(entries, section_label, is_struct):
        nonlocal row
        ws.cell(row=row, column=1, value=section_label)
        style_subheader(ws, row, NC)
        row += 1

        for e in entries:
            name = e["name"]
            changed = set()

            # ── Vanilla values from dump ──
            v_cost = e.get("cost", 0)
            v_build = e.get("build_time", 0)
            v_tier = e.get("min_tier", -1)
            v_hp = e.get("hp", 0)
            move_spd = e.get("move_speed", 0)
            fly_spd = e.get("fly_speed", 0)

            # Creature attacks
            atk_range = e.get("atk_range", 0)
            atk_spread = e.get("atk_spread", 0)
            atk_proj = e.get("atk_proj", "")
            proj_spd = e.get("proj_speed", 0)
            proj_life = e.get("proj_lifetime", 0)
            inst_hit = e.get("instant_hit", False)

            atk2_range = e.get("atk2_range", 0)
            atk2_spread = e.get("atk2_spread", 0)
            atk2_proj = e.get("atk2_proj", "")
            proj2_spd = e.get("proj2_speed", 0)
            proj2_life = e.get("proj2_lifetime", 0)
            inst_hit2 = e.get("instant_hit2", False)

            # Vehicle turret
            vt_intv = e.get("vt_fire_interval", 0)
            vt_spread = e.get("vt_spread", 0)
            vt_mag = e.get("vt_magazine", 0)
            vt_reload = e.get("vt_reload", 0)
            vt2_intv = e.get("vt2_fire_interval", 0)
            vt2_spread = e.get("vt2_spread", 0)
            vt2_mag = e.get("vt2_magazine", 0)

            # Detection
            fow = e.get("fow_view", 0)
            targ_dist = e.get("target_dist", 0)
            max_dist = e.get("max_dist", 0)

            # ── Modded values ──
            m_cost = modded_int(name, v_cost, "cost_mult") if v_cost > 0 else 0
            m_build = round(modded_val(name, v_build, "build_time_mult"), 1) if v_build > 0 else 0
            m_tier_raw = get_cfg(name, "min_tier")
            m_tier = m_tier_raw if m_tier_raw is not None else v_tier
            m_hp = modded_int(name, v_hp, "health_mult") if v_hp > 0 else 0

            # Config multipliers for display
            dmg_m = get_cfg(name, "damage_mult", 1.0)
            spd_m = get_cfg(name, "proj_speed_mult", 1.0)
            rng_m = get_cfg(name, "range_mult", 1.0)
            acc_m = get_cfg(name, "accuracy_mult", 1.0)
            mag_m = get_cfg(name, "magazine_mult", 1.0)
            fr_m = get_cfg(name, "fire_rate_mult", 1.0)
            mv_m = get_cfg(name, "move_speed_mult", 1.0)
            tr_m = get_cfg(name, "turn_radius_mult", 1.0)
            br = get_cfg(name, "build_radius")

            # Config notes
            cfg_note = get_cfg(name, "_note", "")

            # ── Highlight changed cells ──
            if v_cost > 0 and m_cost != v_cost: changed.update({3, 4})
            if v_build > 0 and m_build != v_build: changed.update({5, 6})
            if m_tier != v_tier: changed.update({7, 8})
            if v_hp > 0 and m_hp != v_hp: changed.update({9, 10})
            if dmg_m != 1.0: changed.add(35)
            if spd_m != 1.0: changed.add(36)
            if rng_m != 1.0: changed.add(37)
            if acc_m != 1.0: changed.add(38)
            if mag_m != 1.0: changed.add(39)
            if fr_m != 1.0: changed.add(40)
            if mv_m != 1.0: changed.add(41)
            if tr_m != 1.0: changed.add(42)
            if br is not None: changed.add(43)

            # Clean up projectile names (strip "ProjectileData_" prefix)
            if atk_proj.startswith("ProjectileData_"):
                atk_proj = atk_proj[len("ProjectileData_"):]
            if atk2_proj.startswith("ProjectileData_"):
                atk2_proj = atk2_proj[len("ProjectileData_"):]

            vals = [
                name, e.get("built_at", ""),
                v(v_cost), v(m_cost),
                v(v_build), v(m_build),
                v(v_tier) if v_tier >= 0 else "-",
                v(m_tier) if m_tier >= 0 else "-",
                v(v_hp), v(m_hp),
                v(move_spd), v(fly_spd),
                # Creature primary
                v(atk_range), v(atk_spread), v(atk_proj),
                v(proj_spd), v(proj_life), v(inst_hit),
                # Creature secondary
                v(atk2_range), v(atk2_spread), v(atk2_proj),
                v(proj2_spd), v(proj2_life), v(inst_hit2),
                # Vehicle turret primary
                v(vt_intv), v(vt_spread), v(vt_mag), v(vt_reload),
                # Vehicle turret secondary
                v(vt2_intv), v(vt2_spread), v(vt2_mag),
                # Detection
                v(fow), v(targ_dist), v(max_dist),
                # Mod multipliers (show only if != 1.0)
                v(dmg_m) if dmg_m != 1.0 else "-",
                v(spd_m) if spd_m != 1.0 else "-",
                v(rng_m) if rng_m != 1.0 else "-",
                v(acc_m) if acc_m != 1.0 else "-",
                v(mag_m) if mag_m != 1.0 else "-",
                v(fr_m) if fr_m != 1.0 else "-",
                v(mv_m) if mv_m != 1.0 else "-",
                v(tr_m) if tr_m != 1.0 else "-",
                v(br) if br else "-",
                cfg_note,
            ]
            for ci, val in enumerate(vals, 1):
                ws.cell(row=row, column=ci, value=val)
            style_row(ws, row, NC, is_struct=is_struct, changed=changed)
            row += 1

    write_entries(structures, "── STRUCTURES ──", True)
    write_entries(units, "── UNITS ──", False)

    # Auto-width
    for c in range(1, NC + 1):
        max_len = max(
            len(str(ws.cell(row=r, column=c).value or ""))
            for r in range(1, row)
        )
        ws.column_dimensions[get_column_letter(c)].width = min(max(max_len + 2, 6), 22)

    ws.freeze_panes = "A2"

def write_tech_sheet(wb):
    ws = wb.create_sheet(title="Tech Tiers")
    headers = ["Tier", "Name (Cent)", "Name (Alien)", "Default (s)", "Modded (s)", "Cumul. (s)", "Cumul. (min)"]
    for ci, h in enumerate(headers, 1):
        ws.cell(row=1, column=ci, value=h)
    style_header(ws, 1, HEADER_FILL_TECH, len(headers))

    cent_names = ["Mark I", "Mark II", "Mark III", "Mark IV",
                  "Mark V", "Mark VI", "Mark VII", "Mark VIII"]
    alien_names = ["Alpha I", "Beta II", "Gamma III", "Delta IV",
                   "Theta V", "Lambda VI", "Sigma VII", "Omega VIII"]

    cumulative = 0
    for tier in range(1, 9):
        modded = tech_cfg.get(f"tier_{tier}", DEFAULT_TECH_TIME)
        cumulative += modded
        changed = {4, 5} if modded != DEFAULT_TECH_TIME else set()
        vals = [tier, cent_names[tier-1], alien_names[tier-1],
                DEFAULT_TECH_TIME, modded, cumulative, round(cumulative / 60, 1)]
        row = tier + 1
        for ci, val in enumerate(vals, 1):
            ws.cell(row=row, column=ci, value=val)
        style_row(ws, row, len(headers), changed=changed)

    for c in range(1, len(headers) + 1):
        ws.column_dimensions[get_column_letter(c)].width = 16
    ws.freeze_panes = "A2"

def write_production_tree_sheet(wb):
    """Write production tree as a reference sheet."""
    ws = wb.create_sheet(title="Production Tree")
    headers = ["Producer", "Builds"]
    for ci, h in enumerate(headers, 1):
        ws.cell(row=1, column=ci, value=h)
    style_header(ws, 1, HEADER_FILL_TECH, len(headers))

    row = 2
    for producer in sorted(prod_tree.keys()):
        items = prod_tree[producer]
        ws.cell(row=row, column=1, value=producer)
        ws.cell(row=row, column=2, value=", ".join(items))
        for c in range(1, 3):
            cell = ws.cell(row=row, column=c)
            cell.border = THIN_BORDER
            cell.alignment = Alignment(vertical="center")
        row += 1

    ws.column_dimensions["A"].width = 28
    ws.column_dimensions["B"].width = 80
    ws.freeze_panes = "A2"

# ══════════════════════════════════════════════════════════════
# PER-UNIT WEAPON DETAIL TABS
# ══════════════════════════════════════════════════════════════

WEAPON_FILL = PatternFill("solid", fgColor="D6DCE4")
MODDED_FILL = PatternFill("solid", fgColor="FFFFCC")

def has_weapons(u):
    """Return True if unit has any weapon data (VT or creature attacks)."""
    if u.get("vt_proj") or u.get("vt2_proj"):
        return True
    if u.get("atk_proj") or u.get("atk2_proj"):
        return True
    if u.get("vt_fire_interval", 0) > 0 or u.get("vt2_fire_interval", 0) > 0:
        return True
    if u.get("atk_damage", 0) > 0 or u.get("atk2_damage", 0) > 0:
        return True
    return False

def get_proj_override(name, proj_name, field):
    """Get absolute projectile override from config, or None."""
    entry = units_cfg.get(name, {})
    projs = entry.get("projectiles", {})
    p = projs.get(proj_name, {})
    return p.get(field)

def modded_proj_dmg(name, proj_name, field, vanilla):
    """Get modded damage: absolute override > damage_mult > vanilla."""
    abs_val = get_proj_override(name, proj_name, field)
    if abs_val is not None:
        return abs_val
    dmg_m = get_cfg(name, "damage_mult", 1.0)
    if dmg_m != 1.0 and vanilla > 0:
        return round(vanilla * dmg_m, 1)
    return vanilla

def dmg_source(name, proj, field, van, mod):
    """Return source label for a modded damage value."""
    if van == mod: return "-"
    if get_proj_override(name, proj, field) is not None: return "absolute"
    return "damage_mult"

def write_section(ws, row, label, params):
    """Write a section block with vanilla/modded/source columns. Returns next row."""
    # Section header
    ws.cell(row=row, column=1, value=label)
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=4)
    for c in range(1, 5):
        cell = ws.cell(row=row, column=c)
        cell.font = Font(bold=True, size=10)
        cell.fill = WEAPON_FILL
        cell.border = THIN_BORDER
    row += 1

    # Column headers
    for ci, h in enumerate(["Parameter", "Vanilla", "Modded", "Source"], 1):
        cell = ws.cell(row=row, column=ci, value=h)
        cell.font = Font(bold=True, size=9)
        cell.border = THIN_BORDER
        cell.alignment = Alignment(horizontal="center")
    row += 1

    # Data rows
    for pname, vanilla, modded, source in params:
        ws.cell(row=row, column=1, value=pname)
        ws.cell(row=row, column=2, value=v(vanilla))
        ws.cell(row=row, column=3, value=v(modded))
        ws.cell(row=row, column=4, value=source)
        for c in range(1, 5):
            ws.cell(row=row, column=c).border = THIN_BORDER
            ws.cell(row=row, column=c).alignment = Alignment(horizontal="center" if c > 1 else "left")
        if vanilla != modded and modded not in (0, "-", False, ""):
            ws.cell(row=row, column=3).fill = MODDED_FILL
        row += 1

    return row + 1  # blank row

# ── Helpers for modded value computation ──

def _m(val, mult, source_key):
    """Apply multiplier. Returns (modded, source)."""
    if abs(mult - 1.0) > 0.001 and val > 0:
        return round(val * mult, 2), source_key
    return val, "-"

def _mi(val, mult, source_key):
    """Apply multiplier, round to int. Returns (modded, source)."""
    if abs(mult - 1.0) > 0.001 and val > 0:
        return max(1, round(val * mult)), source_key
    return val, "-"

def _div(val, mult, source_key):
    """Apply divisor (for fire_rate_mult). Returns (modded, source)."""
    if abs(mult - 1.0) > 0.001 and val > 0:
        return round(val / mult, 4), source_key
    return val, "-"

def _ov(val, override, source_key):
    """Apply absolute override. Returns (modded, source)."""
    if override is not None and override != val:
        return override, source_key
    return val, "-"

def _row(label, vanilla, modded, source):
    """Create a param row tuple, auto-detect unchanged."""
    if vanilla == modded:
        source = "-"
    return (label, vanilla, modded, source)

def build_proj_section(name, proj_name, impact_v, ricochet_v, splash_v, pen_v,
                       speed_v, lifetime_v, is_instant, has_splash, has_pen,
                       dmg_m, rng_m, spd_m, proj_overrides):
    """Build projectile parameter list with computed vanilla/modded values."""
    params = []

    # Damage fields
    impact_m = modded_proj_dmg(name, proj_name, "m_fImpactDamage", impact_v)
    ricochet_m = modded_proj_dmg(name, proj_name, "m_fRicochetDamage", ricochet_v)
    splash_m = modded_proj_dmg(name, proj_name, "m_fSplashDamageMax", splash_v)
    pen_m = modded_proj_dmg(name, proj_name, "m_fPenetratingDamage", pen_v)

    params.append(_row("Impact Damage", impact_v, impact_m,
                        dmg_source(name, proj_name, "m_fImpactDamage", impact_v, impact_m)))
    if ricochet_v > 0 or ricochet_m > 0:
        params.append(_row("Ricochet Damage", ricochet_v, ricochet_m,
                            dmg_source(name, proj_name, "m_fRicochetDamage", ricochet_v, ricochet_m)))
    if splash_v > 0 or has_splash:
        params.append(_row("Splash Damage", splash_v, splash_m,
                            dmg_source(name, proj_name, "m_fSplashDamageMax", splash_v, splash_m)))
    if pen_v > 0 or has_pen:
        params.append(_row("Penetrating Dmg", pen_v, pen_m,
                            dmg_source(name, proj_name, "m_fPenetratingDamage", pen_v, pen_m)))

    # Speed / Lifetime / Range
    if is_instant:
        # Instant-hit: m_fBaseSpeed IS the raycast distance (= range)
        m_spd = speed_v
        src_parts = []
        if abs(rng_m - 1.0) > 0.001:
            m_spd *= rng_m
            src_parts.append("range_mult")
        if abs(spd_m - 1.0) > 0.001:
            m_spd *= spd_m
            src_parts.append("proj_speed_mult")
        m_spd = round(m_spd, 1)
        spd_src = "+".join(src_parts) if src_parts else "-"

        params.append(("Instant Hit", "Yes", "Yes", ""))
        params.append(_row("Speed (= Range)", speed_v, m_spd, spd_src))
        if lifetime_v > 0:
            params.append(("Lifetime (visual only)", lifetime_v, lifetime_v, "-"))
        params.append(_row("Effective Range (m)", round(speed_v), round(m_spd), spd_src))
    else:
        # Normal projectile: range = speed * lifetime
        m_spd, spd_src = _m(speed_v, spd_m, "proj_speed_mult")
        m_lt, lt_src = _m(lifetime_v, rng_m, "range_mult")

        params.append(("Instant Hit", "No", "No", ""))
        if speed_v > 0:
            params.append(_row("Proj Speed", speed_v, m_spd, spd_src))
        if lifetime_v > 0:
            params.append(_row("Proj Lifetime (s)", lifetime_v, m_lt, lt_src))

        eff_v = round(speed_v * lifetime_v) if speed_v > 0 and lifetime_v > 0 else 0
        eff_m = round(m_spd * m_lt) if m_spd > 0 and m_lt > 0 else 0
        if eff_v > 0:
            rng_src = "-"
            if eff_v != eff_m:
                parts = []
                if spd_src != "-": parts.append("proj_speed_mult")
                if lt_src != "-": parts.append("range_mult")
                rng_src = "+".join(parts) if parts else "-"
            params.append(_row("Effective Range (m)", eff_v, eff_m, rng_src))

    return params

def write_unit_detail_tab(wb, u):
    """Create a comprehensive detail tab for a single unit."""
    name = u["name"]
    tab_name = name[:31]  # Excel 31 char limit
    existing = [ws.title for ws in wb.worksheets]
    if tab_name in existing:
        tab_name = tab_name[:28] + "..."
    ws = wb.create_sheet(title=tab_name)

    # Title row
    faction = u.get("faction", "?")
    fill_map = {"Sol": HEADER_FILL_SOL, "Centauri": HEADER_FILL_CENT, "Alien": HEADER_FILL_ALIEN}
    title_fill = fill_map.get(faction, HEADER_FILL_TECH)

    ws.cell(row=1, column=1, value=f"{name} — Weapon Detail ({faction})")
    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=4)
    for c in range(1, 5):
        cell = ws.cell(row=1, column=c)
        cell.font = Font(bold=True, color="FFFFFF", size=11)
        cell.fill = title_fill
        cell.border = THIN_BORDER

    # ── Config ──
    cfg = units_cfg.get(name, {})
    dmg_m = cfg.get("damage_mult", 1.0)
    hp_m = cfg.get("health_mult", 1.0)
    cost_m = cfg.get("cost_mult", 1.0)
    bt_m = cfg.get("build_time_mult", 1.0)
    rng_m = cfg.get("range_mult", 1.0)
    spd_m = cfg.get("proj_speed_mult", 1.0)
    acc_m = cfg.get("accuracy_mult", 1.0)
    mag_m = cfg.get("magazine_mult", 1.0)
    fr_m = cfg.get("fire_rate_mult", 1.0)
    rld_m = cfg.get("reload_time_mult", 1.0)
    mv_m = cfg.get("move_speed_mult", 1.0)
    tr_m = cfg.get("turn_radius_mult", 1.0)
    min_tier_ov = cfg.get("min_tier")
    build_rad = cfg.get("build_radius")
    cfg_note = cfg.get("_note", "")

    row = 3

    # ── Overview section ──
    overview = []
    hp = u.get("hp", 0)
    if hp > 0:
        m, s = _mi(hp, hp_m, "health_mult")
        overview.append(_row("HP", hp, m, s))
    cost = u.get("cost", 0)
    if cost > 0:
        m, s = _mi(cost, cost_m, "cost_mult")
        overview.append(_row("Cost", cost, m, s))
    bt = u.get("build_time", 0)
    if bt > 0:
        m, s = _m(bt, bt_m, "build_time_mult")
        overview.append(_row("Build Time (s)", bt, m, s))
    tier = u.get("min_tier", -1)
    if tier >= 0:
        m, s = _ov(tier, min_tier_ov, "min_tier")
        overview.append(_row("Min Tier", tier, m, s))
    ms = u.get("move_speed", 0)
    if ms > 0:
        m, s = _m(ms, mv_m, "move_speed_mult")
        veh_type = u.get("veh_type", "")
        label = "Move Speed (m/s)"
        if veh_type == "Wheeled":
            label = f"Move Speed (m/s, top={round(ms*2.03)})"
        overview.append(_row(label, ms, m, s))
    fs = u.get("fly_speed", 0)
    if fs > 0:
        m, s = _m(fs, mv_m, "move_speed_mult")
        overview.append(_row("Fly Speed (m/s)", fs, m, s))
    # Vehicle-specific movement
    veh_type = u.get("veh_type", "")
    if veh_type == "Wheeled":
        va = u.get("veh_accel", 0)
        if va > 0:
            overview.append(("Wheel Accel (% top/s)", va, va, "-"))
        vr = u.get("veh_reverse_scale", 0)
        if vr > 0:
            overview.append(("Reverse Speed Scale", vr, vr, "-"))
        vtr = u.get("veh_turn_radius", 0)
        if vtr > 0:
            m, s = _m(vtr, tr_m, "turn_radius_mult")
            overview.append(_row("Turn Radius (m)", vtr, m, s))
    elif veh_type == "Hovered":
        va = u.get("veh_accel", 0)
        if va > 0:
            overview.append(("Move Accel (m/s^2)", va, va, "-"))
        vts = u.get("veh_turn_speed", 0)
        if vts > 0:
            overview.append(("Turn Speed (deg/s)", vts, vts, "-"))
    # Soldier movement
    ws_val = u.get("walk_speed", 0)
    rs_val = u.get("run_speed", 0)
    if ws_val > 0:
        m, s = _m(ws_val, mv_m, "move_speed_mult")
        overview.append(_row("Walk Speed", ws_val, m, s))
    if rs_val > 0:
        m, s = _m(rs_val, mv_m, "move_speed_mult")
        overview.append(_row("Run Speed", rs_val, m, s))
    td = u.get("target_dist", 0)
    if td > 0:
        m, s = _m(td, rng_m, "range_mult")
        overview.append(_row("Targeting Distance", td, m, s))
    fow = u.get("fow_view", 0)
    if fow > 0:
        overview.append(("FoW View Distance", fow, fow, "-"))
    if cfg_note:
        overview.append(("Config Note", cfg_note, "", ""))

    if overview:
        row = write_section(ws, row, "Overview", overview)

    # ── VehicleTurret Primary ──
    vt_proj = u.get("vt_proj", "")
    if u.get("vt_fire_interval", 0) > 0 or vt_proj:
        turret = []
        fi = u.get("vt_fire_interval", 0)
        if fi > 0:
            m, s = _div(fi, fr_m, "fire_rate_mult")
            turret.append(_row("Fire Interval (s)", fi, m, s))
        sp = u.get("vt_spread", 0)
        if sp > 0:
            m, s = _m(sp, acc_m, "accuracy_mult")
            turret.append(_row("Muzzle Spread", sp, m, s))
        mg = u.get("vt_magazine", 0)
        if mg > 0:
            m, s = _mi(mg, mag_m, "magazine_mult")
            turret.append(_row("Magazine Size", mg, m, s))
        sc = u.get("vt_shot_count", 0)
        if sc > 0:
            turret.append(("Shot Count", sc, sc, "-"))
        rl = u.get("vt_reload", 0)
        if rl > 0:
            m, s = _m(rl, rld_m, "reload_time_mult")
            turret.append(_row("Reload Time (s)", rl, m, s))
        if turret:
            row = write_section(ws, row, "Primary Turret", turret)

        if vt_proj:
            proj = build_proj_section(name, vt_proj,
                u.get("vt_impact_dmg", 0), u.get("vt_ricochet_dmg", 0),
                u.get("vt_splash_dmg", 0), u.get("vt_pen_dmg", 0),
                u.get("vt_proj_speed", 0), u.get("vt_proj_lifetime", 0),
                u.get("vt_instant_hit", False),
                u.get("vt_has_splash", False), u.get("vt_has_pen", False),
                dmg_m, rng_m, spd_m, cfg.get("projectiles", {}))
            if proj:
                row = write_section(ws, row, f"Projectile: {vt_proj}", proj)

    # ── VehicleTurret Secondary ──
    vt2_proj = u.get("vt2_proj", "")
    if u.get("vt2_fire_interval", 0) > 0 or vt2_proj:
        turret2 = []
        fi = u.get("vt2_fire_interval", 0)
        if fi > 0:
            m, s = _div(fi, fr_m, "fire_rate_mult")
            turret2.append(_row("Fire Interval (s)", fi, m, s))
        sp = u.get("vt2_spread", 0)
        if sp > 0:
            m, s = _m(sp, acc_m, "accuracy_mult")
            turret2.append(_row("Muzzle Spread", sp, m, s))
        mg = u.get("vt2_magazine", 0)
        if mg > 0:
            m, s = _mi(mg, mag_m, "magazine_mult")
            turret2.append(_row("Magazine Size", mg, m, s))
        sc = u.get("vt2_shot_count", 0)
        if sc > 0:
            turret2.append(("Shot Count", sc, sc, "-"))
        rl = u.get("vt2_reload", 0)
        if rl > 0:
            m, s = _m(rl, rld_m, "reload_time_mult")
            turret2.append(_row("Reload Time (s)", rl, m, s))
        if turret2:
            row = write_section(ws, row, "Secondary Turret", turret2)

        if vt2_proj:
            proj = build_proj_section(name, vt2_proj,
                u.get("vt2_impact_dmg", 0), u.get("vt2_ricochet_dmg", 0),
                u.get("vt2_splash_dmg", 0), u.get("vt2_pen_dmg", 0),
                u.get("vt2_proj_speed", 0), u.get("vt2_proj_lifetime", 0),
                u.get("vt2_instant_hit", False),
                u.get("vt2_has_splash", False), u.get("vt2_has_pen", False),
                dmg_m, rng_m, spd_m, cfg.get("projectiles", {}))
            if proj:
                row = write_section(ws, row, f"Projectile: {vt2_proj}", proj)

    # ── Creature Primary Attack ──
    atk_proj = u.get("atk_proj", "")
    if u.get("atk_damage", 0) > 0 or atk_proj:
        atk = []
        ad = u.get("atk_damage", 0)
        if ad > 0:
            m, s = _m(ad, dmg_m, "damage_mult")
            atk.append(_row("Melee/Attack Damage", ad, round(m), s))
        ac = u.get("atk_cooldown", 0)
        if ac > 0:
            atk.append(("Cooldown (s)", ac, ac, "-"))
        ar = u.get("atk_range", 0)
        if ar > 0:
            m, s = _m(ar, rng_m, "range_mult")
            atk.append(_row("AI Range (AimDistMax)", ar, round(m), s))
        asp = u.get("atk_spread", 0)
        if asp > 0:
            m, s = _m(asp, acc_m, "accuracy_mult")
            atk.append(_row("Spread", asp, m, s))
        if atk:
            row = write_section(ws, row, "Primary Attack", atk)

        if atk_proj:
            proj = build_proj_section(name, atk_proj,
                u.get("proj_impact_dmg", 0), u.get("proj_ricochet_dmg", 0),
                u.get("proj_splash_dmg", 0), 0,
                u.get("proj_speed", 0), u.get("proj_lifetime", 0),
                u.get("instant_hit", False), False, False,
                dmg_m, rng_m, spd_m, cfg.get("projectiles", {}))
            if proj:
                row = write_section(ws, row, f"Projectile: {atk_proj}", proj)

    # ── Creature Secondary Attack ──
    atk2_proj = u.get("atk2_proj", "")
    if u.get("atk2_damage", 0) > 0 or atk2_proj:
        atk2 = []
        ad = u.get("atk2_damage", 0)
        if ad > 0:
            m, s = _m(ad, dmg_m, "damage_mult")
            atk2.append(_row("Melee/Attack Damage", ad, round(m), s))
        ac = u.get("atk2_cooldown", 0)
        if ac > 0:
            atk2.append(("Cooldown (s)", ac, ac, "-"))
        ar = u.get("atk2_range", 0)
        if ar > 0:
            m, s = _m(ar, rng_m, "range_mult")
            atk2.append(_row("AI Range (AimDistMax)", ar, round(m), s))
        asp = u.get("atk2_spread", 0)
        if asp > 0:
            m, s = _m(asp, acc_m, "accuracy_mult")
            atk2.append(_row("Spread", asp, m, s))
        if atk2:
            row = write_section(ws, row, "Secondary Attack", atk2)

        if atk2_proj:
            proj = build_proj_section(name, atk2_proj,
                u.get("proj2_impact_dmg", 0), u.get("proj2_ricochet_dmg", 0),
                u.get("proj2_splash_dmg", 0), 0,
                u.get("proj2_speed", 0), u.get("proj2_lifetime", 0),
                u.get("instant_hit2", False), False, False,
                dmg_m, rng_m, spd_m, cfg.get("projectiles", {}))
            if proj:
                row = write_section(ws, row, f"Projectile: {atk2_proj}", proj)

    # Auto-width
    ws.column_dimensions["A"].width = 26
    ws.column_dimensions["B"].width = 18
    ws.column_dimensions["C"].width = 18
    ws.column_dimensions["D"].width = 16

def write_all_unit_detail_tabs(wb):
    """Write per-unit weapon detail tabs for all units with weapons."""
    count = 0
    for u in all_units:
        name = u["name"]
        if name in SKIP_NAMES or is_tech_tier(name):
            continue
        if u.get("team") == "Team_AlienWorms":
            continue
        if not has_weapons(u):
            continue
        write_unit_detail_tab(wb, u)
        count += 1
    return count

# ══════════════════════════════════════════════════════════════
# BUILD
# ══════════════════════════════════════════════════════════════

wb = Workbook()
wb.remove(wb.active)

write_sheet(wb, "Sol", sol_structures, sol_units, HEADER_FILL_SOL)
write_sheet(wb, "Centauri", cent_structures, cent_units, HEADER_FILL_CENT)
write_sheet(wb, "Alien", alien_structures, alien_units, HEADER_FILL_ALIEN)
write_tech_sheet(wb)
write_production_tree_sheet(wb)
detail_count = write_all_unit_detail_tabs(wb)

wb.save(OUTPUT_PATH)
print(f"Saved: {OUTPUT_PATH}")
print(f"Sheets: {wb.sheetnames}")
print(f"Columns per sheet: {NC}")

# Summary
print(f"\nSol: {len(sol_structures)} structures, {len(sol_units)} units")
print(f"Centauri: {len(cent_structures)} structures, {len(cent_units)} units")
print(f"Alien: {len(alien_structures)} structures, {len(alien_units)} units")
print(f"Unit detail tabs: {detail_count}")
